### ISSUE TITLE
Submit grafana dashboards to Grafana.com

### ISSUE THREAD

**Issue by niorg** [rabbitmq/rabbitmq-prometheus#11]
Hi,

Would it be possible to submit the Grafana dashboards in the repository to Grafana.com? That way management and versioning are simpler and easier to automate.

**Comment by michaelklishin** [comment]
They will be submitted shortly, currently undergoing some last minute  touches.

**Comment by gerhard** [comment]
The most useful Grafana dashboard, [RabbitMQ Overview](https://grafana.com/grafana/dashboards/10991) is already public. A few others are also public, more to follow shortly: https://grafana.com/orgs/rabbitmq
