### ISSUE TITLE
Metrics missing for distribution buffer busy limit - zdbbl

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-prometheus#39]
Now that https://github.com/erlang/otp/pull/2270 & https://github.com/deadtrickster/prometheus.erl/pull/94 have been merged and released, we want to expose and visualise the distribution buffer busy limit (a.k.a. [zdbbl](https://erlang.org/doc/man/erl.html#+zdbbl)).

The goal is to be able to measure how busy a particular distribution link is, so that users of RabbitMQ would know when increasing the inter-node communication buffer size would be beneficial. When implemented, this feature will be a good companion to [RabbitMQ Runtime Tuning - Inter-node Communication Buffer Size](https://www.rabbitmq.com/runtime.html#distribution-buffer).

This was created part of https://github.com/rabbitmq/tgir/pull/9. The expectation is that one of the viewers will implement this feature, by following the video. Hopefully, this will inspire others to contribute features & fixes to RabbitMQ 🙌🏻

[Thanks Matt E for reminding us about this outstanding issue](https://groups.google.com/forum/#!topic/rabbitmq-users/F8f26MaFSqY/discussion)

**Comment by michaelklishin** [comment]
Everything is now in place to work on this.

**Comment by gerhard** [comment]
This actually shipped in 3.8.4. I was hoping that someone watching [TGIR S01E04](https://www.youtube.com/watch?v=9q-_DLfhfYg) will contribute it, but didn't want to keep it away from the users that were expecting it, so I shipped it darkly: https://github.com/rabbitmq/rabbitmq-prometheus/commit/17853e35ad114ee3791cdcd1646845a5da370d86

Will close this via PR that adds tests next & back-port to 3.8.x

**Comment by gerhard** [comment]
Back-ported to <kbd>v3.8.x</kbd> via https://github.com/rabbitmq/rabbitmq-prometheus/commit/0612960036d0c0cc29eefe48de224a4db81fc5d4
