### ISSUE TITLE
Add cluster label to metrics

### ISSUE THREAD

**Issue by aitorpazos** [rabbitmq/rabbitmq-prometheus#41]
When you may be running multiple rabbitmq clusters in the same environment in combination with prometheus service discovery mechanisms it become necessary to differentiate the metrics belonging to multiple clusters.

Doing it as https://github.com/kbudde/rabbitmq_exporter does, this is, exposing the cluster name as a label would be enough.

**Comment by gerhard** [comment]
(This is a Prometheus anti-pattern](https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels-not-static-scraped-labels). It felt awkward to me first, but I eventually understood & accepted the reasoning behind it. Context: https://github.com/prometheus/docs/pull/1414#issuecomment-520505757

Related to https://github.com/rabbitmq/rabbitmq-prometheus/issues/50#issuecomment-648880995
